"""Changepoint detection, penalty sweep, segment clustering, and cohort reporting.

Public API re-exports for the GSA feature-group changepoint pipeline.
"""

from .detection import (
    ChangepointConfig,
    ChangepointTables,
    auto_penalty,
    build_signal_matrix,
    compare_breakpoints,
    detect_cohort_changepoints,
    detect_trajectory_changepoints,
    discover_feature_csvs,
    write_changepoint_tables,
)
from .feature_groups import (
    DEFAULT_GROUPS,
    GSA_COLS,
    GROUP_COLORS,
    GROUP_MARKERS,
    IODINE_COLS,
    METADATA_COLS,
    NA_WATER_COLS,
    REGIME_COLS,
    SUMMARY_COLS,
    resolve_group_columns,
    summary_feature_columns,
)
from .penalty_sweep import (
    PenaltySweepConfig,
    PenaltySweepResult,
    default_penalty_grid,
    find_penalty_elbow,
    find_stable_plateaus,
    plot_sweep,
    sweep_penalties,
    write_sweep_artifacts,
)
from .pipeline import ChangepointPipeline
from .reporting import (
    DEFAULT_TIMELINE_PANELS,
    plot_breakpoint_histogram,
    plot_cluster_representative_timelines,
    plot_cohort_breakpoints_all_trajectories,
    plot_cohort_traces_normalized_all_trajectories,
    plot_jaccard_heatmap,
    plot_timeline,
    summarize_changepoint_results,
    write_cohort_tables,
)
from .segment_clustering import (
    SegmentClusteringConfig,
    build_feature_matrix_from_segments_df,
    build_segment_feature_matrix,
    cluster_all_groups,
    cluster_segment_group,
    load_segment_stats,
    write_cohort_cluster_outputs,
)

__all__ = [
    "ChangepointConfig",
    "ChangepointPipeline",
    "ChangepointTables",
    "DEFAULT_GROUPS",
    "DEFAULT_TIMELINE_PANELS",
    "GSA_COLS",
    "GROUP_COLORS",
    "GROUP_MARKERS",
    "IODINE_COLS",
    "METADATA_COLS",
    "NA_WATER_COLS",
    "PenaltySweepConfig",
    "PenaltySweepResult",
    "REGIME_COLS",
    "SUMMARY_COLS",
    "SegmentClusteringConfig",
    "auto_penalty",
    "build_feature_matrix_from_segments_df",
    "build_segment_feature_matrix",
    "build_signal_matrix",
    "cluster_all_groups",
    "cluster_segment_group",
    "compare_breakpoints",
    "default_penalty_grid",
    "detect_cohort_changepoints",
    "detect_trajectory_changepoints",
    "discover_feature_csvs",
    "find_penalty_elbow",
    "find_stable_plateaus",
    "load_segment_stats",
    "plot_breakpoint_histogram",
    "plot_cluster_representative_timelines",
    "plot_cohort_breakpoints_all_trajectories",
    "plot_cohort_traces_normalized_all_trajectories",
    "plot_jaccard_heatmap",
    "plot_sweep",
    "plot_timeline",
    "resolve_group_columns",
    "summarize_changepoint_results",
    "summary_feature_columns",
    "sweep_penalties",
    "write_changepoint_tables",
    "write_cohort_cluster_outputs",
    "write_cohort_tables",
    "write_sweep_artifacts",
]
